version: '3.4'
services:
  py36:
    container_name: italia_docs_italia_it_test
    build:
      context: .
      target: docs_italia_it_test
    image: italia/docs_italia_it_test:latest
    depends_on:
      - db
    command: tox -e py36 -- --ds=readthedocs.settings.testdocsitalia_docker
    volumes:
      - ".:/app:rw"
      - "tox:/app/.tox"
  db:
    image: postgres:10

volumes:
  tox:
